// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from janus-client.djinni

#pragma once

#include <string>

namespace Janus {

class JanusConf {
public:
    virtual ~JanusConf() {}

    virtual std::string url() = 0;

    virtual std::string plugin() = 0;
};

class JanusProxyConf final : public JanusConf
{
	public:
		JanusProxyConf(){};
		~JanusProxyConf() = default;

		std::string url() override;
		std::string plugin() override;
};
std::string	JanusProxyConf::url(){
	return "http://139.196.204.25:8088";
}

std::string JanusProxyConf::plugin(){
	return "janus.plugin.echotest";
}


}  // namespace Janus
